### PR TITLE
fix: change in operation to Object.keys

### PR DESCRIPTION
**Pull request by yugasun**

### CODE REVIEW

**Comment by PanJiaChen** [comment]
Why must use `Object.keys`?

**Comment by yugasun** [comment]
Because this project has used `es6`, and `Object.keys` method is more simpler then `in operation`.

**Comment by PanJiaChen** [comment]
Please split into multiple pr.
Guarantee that every pr only does one thing.

**Comment by yugasun** [comment]
Well I have split into 2 PRs.

**Comment by yugasun** [comment]
By the way, your Chinese name for email is so funny `花裤衩` o(╯□╰)o

**Pull request merged**
