### PR TITLE
refine 路由表从服务器加载 && 角色权限管理

### PR DESCRIPTION
**Pull request by gaoshijun1993**
1.路由表改为从服务器加载, 每个路由配置项增加id和parentId两个字段, components字段改为组件的本地路径
2.增加角色权限管理菜单

### CODE REVIEW

**Comment by PanJiaChen** [comment]
role-tree

**Comment by daweiyong** [comment]
> 1.路由表改为从服务器加载, 每个路由配置项增加id和parentId两个字段, components字段改为组件的本地路径
> 2.增加角色权限管理菜单
我现在的需求，和你的差不多，请问你怎么解决的，谢谢，我后台来的路由大概是这样的，您看一下。
[{
	"id": 13,
	"parentId": -1,
	"children": [{
		"id": 5,
		"parentId": 13,
		"children": [{
			"id": 1,
			"parentId": 5,
			"children": [],
			"icon": "fa-user",
			"title": "用户管理11",
			"href": "/admin/user",
			"spread": false,
			"path": "/adminSys/baseManager/userManager",
			"code": "userManager"
		}, {
			"id": 6,
			"parentId": 5,
			"children": [],
			"icon": "category",
			"title": "菜单管理",
			"href": "/admin/menu",
			"spread": false,
			"path": "/adminSys/baseManager/menuManager",
			"code": "menuManager"
		}, {
			"id": 7,
			"parentId": 5,
			"children": [],
			"icon": "group_fill",
			"title": "角色权限管理",
			"href": "/admin/group",
			"spread": false,
			"path": "/adminSys/baseManager/groupManager",
			"code": "groupManager"
		}, {
			"id": 8,
			"parentId": 5,
			"children": [],
			"icon": "fa-users",
			"title": "角色类型管理",
			"href": "/admin/groupType",
			"spread": false,
			"path": "/adminSys/baseManager/groupTypeManager",
			"code": "groupTypeManager"
		}, {
			"id": 27,
			"parentId": 5,
			"children": [],
			"icon": "viewlist",
			"title": "操作日志",
			"href": "/admin/gateLog",
			"spread": false,
			"path": "/adminSys/baseManager/gateLogManager",
			"code": "gateLogManager"
		}],
		"icon": "setting",
		"title": "基础配置管理",
		"href": "/admin",
		"spread": false,
		"path": "/adminSys/baseManager",
		"code": "baseManager"
	}, {
		"id": 29,
		"parentId": 13,
		"children": [{
			"id": 30,
			"parentId": 29,
			"children": [],
			"icon": "client",
			"title": "服务管理",
			"href": "/auth/service",
			"spread": false,
			"path": "/adminSys/authManager/serviceManager",
			"code": "serviceManager"
		}],
		"icon": "service",
		"title": "服务权限管理",
		"href": "/auth",
		"spread": false,
		"path": "/adminSys/authManager",
		"code": "authManager"
	}, {
		"id": 31,
		"parentId": 13,
		"children": [{
			"id": 32,
			"parentId": 31,
			"children": [],
			"icon": "client",
			"title": "服务注册中心",
			"spread": false,
			"path": "/adminSys/monitorManager/serviceEurekaManager",
			"code": "serviceEurekaManager"
		}, {
			"id": 33,
			"parentId": 31,
			"children": [],
			"icon": "client",
			"title": "服务状态监控",
			"spread": false,
			"path": "/adminSys/monitorManager/serviceEurekaManager",
			"code": "serviceMonitorManager"
		}, {
			"id": 34,
			"parentId": 31,
			"children": [],
			"icon": "client",
			"title": "服务链路监控",
			"spread": false,
			"path": "/adminSys/monitorManager/serviceZipkinManager",
			"code": "serviceZipkinManager"
		}],
		"icon": "service",
		"title": "监控模块管理",
		"spread": false,
		"path": "/adminSys/monitorManager",
		"code": "monitorManager"
	}],
	"icon": "setting",
	"title": "权限管理系统",
	"href": "/base",
	"spread": false,
	"path": "/adminSys",
	"code": "adminSys"
}]

**Comment by mobility2015** [comment]
> > 1.路由表改为从服务器加载, 每个路由配置项增加id和parentId两个字段, components字段改为组件的本地路径
> > 2.增加角色权限管理菜单
> > 我现在的需求，和你的差不多，请问你怎么解决的，谢谢，我后台来的路由大概是这样的，您看一下。
> > [{
> > "id": 13,
> > "parentId": -1,
> > "children": [{
> > "id": 5,
> > "parentId": 13,
> > "children": [{
> > "id": 1,
> > "parentId": 5,
> > "children": [],
> > "icon": "fa-user",
> > "title": "用户管理11",
> > "href": "/admin/user",
> > "spread": false,
> > "path": "/adminSys/baseManager/userManager",
> > "code": "userManager"
> > }, {
> > "id": 6,
> > "parentId": 5,
> > "children": [],
> > "icon": "category",
> > "title": "菜单管理",
> > "href": "/admin/menu",
> > "spread": false,
> > "path": "/adminSys/baseManager/menuManager",
> > "code": "menuManager"
> > }, {
> > "id": 7,
> > "parentId": 5,
> > "children": [],
> > "icon": "group_fill",
> > "title": "角色权限管理",
> > "href": "/admin/group",
> > "spread": false,
> > "path": "/adminSys/baseManager/groupManager",
> > "code": "groupManager"
> > }, {
> > "id": 8,
> > "parentId": 5,
> > "children": [],
> > "icon": "fa-users",
> > "title": "角色类型管理",
> > "href": "/admin/groupType",
> > "spread": false,
> > "path": "/adminSys/baseManager/groupTypeManager",
> > "code": "groupTypeManager"
> > }, {
> > "id": 27,
> > "parentId": 5,
> > "children": [],
> > "icon": "viewlist",
> > "title": "操作日志",
> > "href": "/admin/gateLog",
> > "spread": false,
> > "path": "/adminSys/baseManager/gateLogManager",
> > "code": "gateLogManager"
> > }],
> > "icon": "setting",
> > "title": "基础配置管理",
> > "href": "/admin",
> > "spread": false,
> > "path": "/adminSys/baseManager",
> > "code": "baseManager"
> > }, {
> > "id": 29,
> > "parentId": 13,
> > "children": [{
> > "id": 30,
> > "parentId": 29,
> > "children": [],
> > "icon": "client",
> > "title": "服务管理",
> > "href": "/auth/service",
> > "spread": false,
> > "path": "/adminSys/authManager/serviceManager",
> > "code": "serviceManager"
> > }],
> > "icon": "service",
> > "title": "服务权限管理",
> > "href": "/auth",
> > "spread": false,
> > "path": "/adminSys/authManager",
> > "code": "authManager"
> > }, {
> > "id": 31,
> > "parentId": 13,
> > "children": [{
> > "id": 32,
> > "parentId": 31,
> > "children": [],
> > "icon": "client",
> > "title": "服务注册中心",
> > "spread": false,
> > "path": "/adminSys/monitorManager/serviceEurekaManager",
> > "code": "serviceEurekaManager"
> > }, {
> > "id": 33,
> > "parentId": 31,
> > "children": [],
> > "icon": "client",
> > "title": "服务状态监控",
> > "spread": false,
> > "path": "/adminSys/monitorManager/serviceEurekaManager",
> > "code": "serviceMonitorManager"
> > }, {
> > "id": 34,
> > "parentId": 31,
> > "children": [],
> > "icon": "client",
> > "title": "服务链路监控",
> > "spread": false,
> > "path": "/adminSys/monitorManager/serviceZipkinManager",
> > "code": "serviceZipkinManager"
> > }],
> > "icon": "service",
> > "title": "监控模块管理",
> > "spread": false,
> > "path": "/adminSys/monitorManager",
> > "code": "monitorManager"
> > }],
> > "icon": "setting",
> > "title": "权限管理系统",
> > "href": "/base",
> > "spread": false,
> > "path": "/adminSys",
> > "code": "adminSys"
> > }]

你好，请问这个问题解决了吗？能分享一下解决方法吗？谢谢。

**Comment by huangshizhan** [comment]
同问

**Pull request merged**
