### PR TITLE
V4.0

### PR DESCRIPTION
**Pull request by PanJiaChen**

### CODE REVIEW

**Comment by yashanet** [comment]
Hi, when will be 4.0 release ?
Thanks

**Comment by PanJiaChen** [comment]
@yashanet 
Sorry, the time is not certain. I have been busy with work recently, and most of my energy is not on the front end now.

**Comment by yashanet** [comment]
Any dates to realese v4.0 ?

**Comment by PanJiaChen** [comment]
@yashanet Probably in March.

**Pull request merged**
